#!/bin/bash
#
# Wrapper script for feh to browse an entire folder when opening a single file.
#
# Written by Nicolai Andrew Singh, 2013
#

if [ -n "$1" ]; then
    file="$1"
    dir="${file%/*}"          # remove filename from path

    if [ -f "$file" ]; then
        feh --image-bg black --scale-down --geometry 640x480 --start-at "$file" "$dir" &
        exit 0
    fi
fi

echo 'File not found'
exit 0

