#!/bin/bash
#
# Continuously retrieves gmail information from Gmail using curl and writes
# them in a file.
#
# From: https://gist.github.com/smlb/7dca4b684ca52a2491d1
#
# Written by Nicolai Andrew Singh, 2014
#

user=username
pass=password
sleeptime=1800

while true
do
	echo '(Fetching)' > ~/.gmail
	pkill -RTMIN+2 i3blocks

	gmailinfo=`curl -su $user:$pass https://mail.google.com/mail/feed/atom`
	gmailinfo=`echo "$gmailinfo" | grep -o "<fullcount>.*</fullcount>"`

	if [ -n "$gmailinfo" ]; then
		gmailinfo=`echo $gmailinfo | sed -e s/"<fullcount>"// -e s/"<\/fullcount>"//`
		case $gmailinfo in
		1)
			gmailinfo=`echo $gmailinfo Unread Mail`
			;;
		0)
			gmailinfo='No New Mail'
			;;
		*)
			gmailinfo=`echo $gmailinfo Unread Mails`
			;;
		esac
	else
		gmailinfo=N/A
	fi

	echo "$gmailinfo"> ~/.gmail

	pkill -RTMIN+2 i3blocks

	# sleep until next update
	sleep $sleeptime
done

