#!/usr/bin/env bash
#
# Convert images in SRCDIR to a lower quality then put them in DSTDIR.
#
# The script will check missing files which are not yet in DSTDIR, and
# will only process those files.  Use variables IMG_QUALITY to specify
# the preferred image quality (0-100), and IMG_WIDTH for the preferred
# image width (the aspect ratio is retained).
#
# Edit the FILE_EXTENSIONS variable to specify which image file
# formats will be checked.

# Paths
SRCDIR=/run/media/nas/nas-deskdrv/files
DSTDIR=/run/media/nas/nas-deskdrv/files-low

# Image output properties
IMG_QUALITY=70
IMG_WIDTH=1280

# File extensions to convert
FILE_EXTENSIONS=(png jpg)

##### DON'T CHANGE ANYTHING BELOW UNLESS YOU KNOW WHAT YOU ARE DOING #####

echo $(basename "$0"): $(date)

find_opts=()
for i in "${FILE_EXTENSIONS[@]}"; do
    if [ ${#find_opts[@]} -eq 0 ]; then
        find_opts+=(-iname "*.$i")
    else
        find_opts+=(-o -iname "*.$i")
    fi
done
find_opts=(-type f \( "${find_opts[@]}" \))

x=$(find "$SRCDIR" "${find_opts[@]}" -printf '%P\n' | sort)
y=$(find "$DSTDIR" "${find_opts[@]}" -printf '%P\n' | sort)

newfiles=$(diff --new-line-format='%<' --unchanged-line-format='' \
                <(find "$SRCDIR" ${find_opts[@]} -printf '%P\n' | sort) \
                <(find "$DSTDIR" ${find_opts[@]} -printf '%P\n' | sort))

echo "Starting convert..."
if [ -z "$newfiles" ]; then
    echo "[with-resize] No new files found"
else
    echo "Found $(wc -l <<< "$newfiles") new files"

    while read filepath
    do
        echo "=> Converting $filepath"
        mkdir -p "$DSTDIR/$(dirname "$filepath")"
        magick -quality $IMG_QUALITY -resize $IMG_WIDTH "$SRCDIR/$filepath" "$DSTDIR/$filepath"
    done <<< "$newfiles"
fi

echo -e
echo "Starting convert with no resize (for images smaller than ${IMG_WIDTH})..."
newfiles=$(diff --new-line-format='%<' --unchanged-line-format='' \
                <(find "$SRCDIR" ${find_opts[@]} -printf '%P\n' | sort) \
                <(find "$DSTDIR" ${find_opts[@]} -printf '%P\n' | sort))

if [ -z "$newfiles" ]; then
    echo "[no-resize] Nothing to process"
else
    echo "Found $(wc -l <<< "$newfiles") new files"

    while read filepath
    do
        echo "=> Converting $filepath"
        mkdir -p "$DSTDIR/$(dirname "$filepath")"
        magick -quality $IMG_QUALITY "$SRCDIR/$filepath" "$DSTDIR/$filepath"
    done <<< "$newfiles"
fi
