#!/usr/bin/env bash
#
# A script to apply ReplayGain information to ogg vorbis files using
# vorbisgain. Both track and album gain are applied to reach target level 89dB.
#
# Written by Nicolai Andrew Singh, 2013
#

# music collection folder structure:
# [0] <root>/
# [1] |__ artist/
# [2]     |__ album (<year>)/
# [3]         |__ <artist> - <#> - <title>.ogg
# [3]         |__ <artist> - <#> - <title>.ogg
# [#]             ...
#

# setup target directory
targetdir='/home/nas/Music/library'

vorbisgain_bin=`which vorbisgain`
mp3gain_bin=`which mp3gain`

function _help
{
	echo A script to apply ReplayGain information to ogg vorbis files using vorbisgain.
	echo Both track and album gain are applied to reach target level 89dB.
	echo
	echo Usage:
	echo Use "oggnormalize -a" to normalize _all_ files in target dir.
	echo Use "oggnormalize" to normalize only files in target dir without RG data.
}


[[ $1 = "--help" ]] && _help && exit 0
[[ $1 = "-help" ]] && _help && exit 0
[[ $1 = "-h" ]] && _help && exit 0

dirlist=$(find "$targetdir" -mindepth 3 -type d \
	       -not -path '*/library/mp3*' \
	       -not -path '*/library/all*' \
	      | sort)

# temporarily remove the space character in IFS to avoid
# splitting paths with spaces while iterating through them
oIFS="$IFS"
IFS=`echo -en '\n\b'`

for d in $dirlist
do
    $vorbisgain_bin -a -f -q $d/*.ogg

    ls "$d"/*.mp3 >/dev/null 2>&1
    if [ $? -eq 0 ]; then
	$mp3gain_bin -a -k -q $d/*.mp3
    fi
done


# revert now to the original IFS
IFS="$oIFS"
