#!/bin/bash
#
# Convert Quod Libet playlists to mpd-compatible m3u playlists and
# dump them to a directory.
#
# Quod Libet's playlists are in absolute paths which makes it hard to
# be portable.  This script will create new playlist files in m3u
# format with relative paths by removing PLENT_REPLACE.

PLDIR_QUODLIBET="PLAYLIST_DIR"
PLDIR_MPD="PLAYLIST_DIR"
PLENT_REPLACE="MUSIC_DIR"

mkdir -p "$PLDIR_MPD"
cnt=0

# Backup existing playlists
dt=$(date "+%Y%m%d%H%M")
mkdir -p "$PLDIR_MPD/playlists-bak"
while read file
do
	mv "$file" "$PLDIR_MPD/playlists-bak/$(basename $file).$dt.old"
done <<< $(find "$PLDIR_MPD" -type f -name '*.m3u')

# Do the conversion
while read file
do
	cp "$file" "$PLDIR_MPD/$(basename $file).m3u"
	((++cnt))
done <<< $(find "$PLDIR_QUODLIBET" -type f)

sed -i "s:$PLENT_REPLACE::g" $PLDIR_MPD/*.m3u

echo "Done.  Files processed: $cnt"
